### ISSUE TITLE
Url to thumbnail does not work

### ISSUE THREAD

**Issue by seskildsen** [Dataforsyningen/skraafoto_tile_public#4]
When clicking on the thumbnail url example from here `https://api.dataforsyningen.dk/skraafotoapi_test/collections/skraafotos2019/items/2019_83_37_2_0046_00001113?token=` then this call `https://api.dataforsyningen.dk/skraafoto_cogtiler_test/thumbnail.jpg?url=https%3A%2F%2Fapi.dataforsyningen.dk%2Fskraafoto_server_test%2FCOG_oblique_2019%2F10km_613_58%2F1km_6131_580%2F2019_83_37_2_0046_00001113.tif%3Ftoken%&token=` returns an error saying `not found`

**Comment by AsgerPetersen** [comment]
Probably either a bad url or an intermittent problem. Seems to work now...
